---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >> ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i tests/inventory tests/test.yml -e 'nolog=False' --connection=local

  # Idempotent check
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*unreachable=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Verify final results
  - id test1 | grep -q 'uid=1523(test1) gid=1523(test1) groups=1523(test1)'
  - egrep  "test1|test2|test3" /etc/passwd | wc -l | awk '{exit $1!=2 }'
  - egrep  "test1|test2|test3" /etc/group | wc -l | awk '{exit $1!=2 }'
  - grep '$6$sT17slTs$pgjOlA6AbfOrSI96l5uTkndM0tD8X2XacqLNYKNPkvuTmkHZaqdcteUo2b6VSfU616f3wjeBut5jM6VaDYnvC1' /etc/shadow |grep -q test1
  - grep 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYVWqWp3YNQJMqSxbEB0lfVsqCeBlkeUxTECHCjj43SY+7Ygb' /home/test2/.ssh/authorized_keys |grep -q 'vagrant@node2' 
  - ls -la /etc/sudoers.d/test1 && ls -laq /etc/sudoers.d/test2
  - grep -q 'ALL=(root)       NOPASSWD:/bin/ping' /etc/sudoers.d/test2
  - crontab -l |grep -q '/etc/init.d/enable_test1 stop'
  - /etc/init.d/enable_test1 start 


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

